version: 2.1
# npm version [<newversion> | major | minor | patch]
# git push --tags

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  test-and-publish:
    jobs:
      - node/test:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - node/test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
